_wandb:
    value:
        cli_version: 0.23.1
        code_path: code/ece571n/hm4/hm4_code/td3_continuous_action.py
        e:
            lou4hb2qb1hkt4snrlelg76sidsac0he:
                codePath: ece571n/hm4/hm4_code/td3_continuous_action.py
                codePathLocal: td3_continuous_action.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "56106856448"
                        used: "28559093760"
                email: klukasdominic@gmail.com
                executable: /home/dominic/Projects/equivariant-rl/.venv/bin/python3
                git:
                    commit: e6a1dcbf238f252224e16d69f6aeb406e8efbc60
                    remote: git@github.com:DominicKlukas/gradschool.git
                host: dominic-work
                memory:
                    total: "16478453760"
                os: Linux-6.17.7-arch1-1-x86_64-with-glibc2.42
                program: /home/dominic/gradschool/ece571n/hm4/hm4_code/td3_continuous_action.py
                python: CPython 3.11.14
                root: /home/dominic/gradschool/ece571n/hm4/hm4_code
                startedAt: "2025-12-08T21:54:33.281438Z"
                writerId: lou4hb2qb1hkt4snrlelg76sidsac0he
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
                - 35
            "4": 3.11.14
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
batch_size:
    value: 256
buffer_size:
    value: 1000000
capture_video:
    value: true
cuda:
    value: true
env_id:
    value: HalfCheetah-v4
exp_name:
    value: td3_continuous_action
exploration_noise:
    value: 0.1
gamma:
    value: 0.99
hf_entity:
    value: ""
learning_rate:
    value: 0.0003
learning_starts:
    value: 25000
noise_clip:
    value: 0.5
num_envs:
    value: 1
policy_frequency:
    value: 2
policy_noise:
    value: 0.2
save_model:
    value: false
seed:
    value: 1
tau:
    value: 0.005
torch_deterministic:
    value: true
total_timesteps:
    value: 500000
track:
    value: true
upload_model:
    value: false
wandb_entity:
    value: null
wandb_project_name:
    value: cleanRL
